robbiejaeger/rails_engine

Schema XML.xml
Add xml file generated by schema desginer
=> Add schema designer file

app/models/customer.rb, app/models/merchant.rb, db/migrate/20160718210144_create_customers.rb, db/migrate/20160718210334_create_merchants.rb, db/schema.rb, lib/tasks/import_csv.rake, spec/models/customer_spec.rb, spec/models/merchant_spec.rb
Added rake task for customer with model
Added rake task for merchant with model
=> Create rake task for customers

app/models/invoice.rb, app/models/invoice_item.rb, app/models/item.rb, app/models/transaction.rb, db/migrate/20160718213015_create_items.rb, db/migrate/20160718213558_create_invoices.rb, db/migrate/20160718213820_create_invoice_items.rb, db/migrate/20160718214336_create_transactions.rb, db/migrate/20160718215924_change_card_number.rb, db/schema.rb, lib/tasks/import_csv.rake, spec/models/invoice_item_spec.rb, spec/models/invoice_spec.rb, spec/models/item_spec.rb, spec/models/transaction_spec.rb
Create additional rake tasks to import various CSV data files
=> Add data import tasks

app/models/customer.rb, app/models/invoice.rb, app/models/invoice_item.rb, app/models/item.rb, app/models/merchant.rb, lib/tasks/import_csv.rake
Added group rake task to import all csv files
Added relationships for each model
=> Add combined rake task and model relationships

Gemfile, Gemfile.lock, app/controllers/api/v1/merchants_controller.rb, app/controllers/application_controller.rb, config/routes.rb
Added api routes and controller folder structure
Added merchants controller and index endpoint
Added jbuilder and responders gem
Added Mime::Responders module to application controller
=> Add merchants index endpoint

app/controllers/api/v1/invoices/find_controller.rb, app/controllers/api/v1/invoices/random_controller.rb, app/controllers/api/v1/invoices_controller.rb, config/routes.rb
Implement the `find`, `find_all` and `random` functions for Invoice.
*Add a 'FindController' to handle the `find` and `find_all`. 
*Add a 'RandomController` to handle the `random` function. 
*Add routes for the functions according to the spec
=> Find and random endpoints working

app/controllers/api/v1/invoices/find_controller.rb, app/controllers/api/v1/invoices/random_controller.rb, app/controllers/api/v1/invoices_controller.rb, app/controllers/api/v1/items_controller.rb, config/routes.rb
Implement the record endpoint for Items. Implement the index and show functions
*Add an ItemsController for the `index` and `show` functions. 
*Add routes to support these functions
=> Item index endpoint

app/controllers/api/v1/invoice_items_controller.rb, config/routes.rb
Add functionality for the `index` and `show` methods for InvoiceItem
*Add an InvoiceItem controller to handle the `index` and `show`
*Add routes to support these actions
=> Invoice item index and show working

app/controllers/api/v1/customers/find_controller.rb, app/controllers/api/v1/customers/random_controller.rb, app/controllers/api/v1/customers_controller.rb, app/controllers/api/v1/merchants/find_controller.rb, app/controllers/api/v1/merchants/random_controller.rb, app/controllers/api/v1/merchants_controller.rb, app/controllers/api/v1/transactions/find_controller.rb, app/controllers/api/v1/transactions_controller.rb, app/views/api/v1/customers/find/index.json.jbuilder, app/views/api/v1/customers/find/show.json.jbuilder, app/views/api/v1/customers/index.json.jbuilder, app/views/api/v1/customers/random/show.json.jbuilder, app/views/api/v1/customers/show.json.jbuilder, app/views/api/v1/merchants/find/index.json.jbuilder, app/views/api/v1/merchants/find/show.json.jbuilder, app/views/api/v1/merchants/index.json.jbuilder, app/views/api/v1/merchants/random/show.json.jbuilder, app/views/api/v1/merchants/show.json.jbuilder, app/views/api/v1/transactions/find/index.json.jbuilder, app/views/api/v1/transactions/find/show.json.jbuilder, app/views/api/v1/transactions/index.json.jbuilder, app/views/api/v1/transactions/random/show.json.jbuilder, app/views/api/v1/transactions/show.json.jbuilder
Added jbuilder views for transactions, customers, and merchants to match spec harness
=> Add jbuilder for transactions, customers, and merchants

app/controllers/api/v1/invoice_items/invoices_controller.rb, app/controllers/api/v1/invoice_items/items_controller.rb, app/controllers/api/v1/invoice_items/random_controller.rb, app/controllers/api/v1/invoices/customers_controller.rb, app/controllers/api/v1/invoices/invoice_items_controller.rb, app/controllers/api/v1/invoices/items_controller.rb, app/controllers/api/v1/invoices/merchants_controller.rb, app/controllers/api/v1/invoices/transactions_controller.rb, app/controllers/api/v1/items/invoice_items_controller.rb, app/controllers/api/v1/items/merchants_controller.rb, app/controllers/api/v1/transactions_controller.rb, app/views/api/v1/invoice_items/invoices/show.json.jbuilder, app/views/api/v1/invoice_items/items/show.json.jbuilder, app/views/api/v1/invoices/customers/show.json.jbuilder, app/views/api/v1/invoices/invoice_items/index.json.jbuilder, app/views/api/v1/invoices/items/index.json.jbuilder, app/views/api/v1/invoices/merchants/show.json.jbuilder, app/views/api/v1/invoices/transactions/index.json.jbuilder, app/views/api/v1/items/invoice_items/index.json.jbuilder, app/views/api/v1/items/merchants/show.json.jbuilder, config/routes.rb
Added all association endpoints for Person A
=> Add person a associations

spec/controllers/api/v1/items_find_controller_index_spec.rb
Add a test for the Items/FindController#index action
=> Item FindController#index method test

app/controllers/api/v1/invoices/find_controller.rb, app/views/api/v1/invoices/find/index.json.jbuilder, app/views/api/v1/invoices/find/show.json.jbuilder, spec/controllers/api/v1/invoices_controller_controller_spec.rb, spec/controllers/api/v1/invoices_find_controller_index_spec.rb, spec/controllers/api/v1/invoices_find_controller_show_spec.rb, spec/controllers/api/v1/items_find_controller_index_spec.rb
Convert Invoice Record endpoint to return jbuilder view for show. Test this view.
=> 19 invoice jbuilder record endpoint

spec/controllers/api/v1/items_find_controller_show_spec.rb
Modified test for Items/FindController#show to check 'name' of items returned
=> Added name field check to test

app/controllers/api/v1/invoice_items/find_controller.rb, app/controllers/api/v1/invoice_items_controller.rb, app/views/api/v1/invoice_items/find/index.json.jbuilder, app/views/api/v1/invoice_items/find/show.json.jbuilder, spec/controllers/api/v1/invoice_items_find_controller_index_spec.rb, spec/controllers/api/v1/invoice_items_find_controller_show_spec.rb, spec/controllers/api/v1/items_find_controller_show_spec.rb, spec/factories/factories.rb
Implement Jbuilder for InvoiceItems/FindController `index` and `show` actions. Create tests for these actions.
=> 20 add jbuilder invoice items find controller

app/controllers/api/v1/invoice_items/find_controller.rb, app/controllers/api/v1/invoice_items_controller.rb, app/views/api/v1/invoice_items/find/index.json.jbuilder, app/views/api/v1/invoice_items/find/show.json.jbuilder, spec/controllers/api/v1/invoice_items_find_controller_index_spec.rb, spec/controllers/api/v1/invoice_items_find_controller_show_spec.rb, spec/controllers/api/v1/items_find_controller_index_spec.rb, spec/controllers/api/v1/items_find_controller_show_spec.rb, spec/factories/factories.rb
Add missing checks for the `created_at` and `updated_at` fields not being returned
=> 32 add expect dates nil to tests

app/controllers/api/v1/invoice_items/find_controller.rb, app/controllers/api/v1/invoice_items_controller.rb, app/controllers/api/v1/items_controller.rb, app/views/api/v1/invoice_items/find/index.json.jbuilder, app/views/api/v1/invoice_items/find/show.json.jbuilder, spec/controllers/api/v1/invoice_items_find_controller_index_spec.rb, spec/controllers/api/v1/invoice_items_find_controller_show_spec.rb, spec/controllers/api/v1/items_controller_index_spec.rb, spec/controllers/api/v1/items_controller_show_spec.rb, spec/controllers/api/v1/items_find_controller_index_spec.rb, spec/controllers/api/v1/items_find_controller_show_spec.rb, spec/factories/factories.rb
Create test for ItemsController#show
=> 35 add tests for items controller endpoints

app/controllers/api/v1/invoice_items/find_controller.rb, app/controllers/api/v1/invoice_items_controller.rb, app/controllers/api/v1/invoices_controller.rb, app/controllers/api/v1/items_controller.rb, app/views/api/v1/invoice_items/find/index.json.jbuilder, app/views/api/v1/invoice_items/find/show.json.jbuilder, app/views/api/v1/invoices/index.json.jbuilder, app/views/api/v1/invoices/show.json.jbuilder, spec/controllers/api/v1/invoice_items_find_controller_index_spec.rb, spec/controllers/api/v1/invoice_items_find_controller_show_spec.rb, spec/controllers/api/v1/invoices_controller_index_spec.rb, spec/controllers/api/v1/invoices_controller_show_spec.rb, spec/controllers/api/v1/invoices_find_controller_show_spec.rb, spec/controllers/api/v1/items_controller_index_spec.rb, spec/controllers/api/v1/items_controller_show_spec.rb, spec/controllers/api/v1/items_find_controller_index_spec.rb, spec/controllers/api/v1/items_find_controller_show_spec.rb, spec/factories/factories.rb
Add test for InvoicesController#show
=> 36 add tests for invoices controller endpoints

app/controllers/api/v1/invoice_items/find_controller.rb, app/controllers/api/v1/invoice_items_controller.rb, app/controllers/api/v1/invoices_controller.rb, app/controllers/api/v1/items_controller.rb, app/views/api/v1/invoice_items/find/index.json.jbuilder, app/views/api/v1/invoice_items/find/show.json.jbuilder, app/views/api/v1/invoice_items/index.json.jbuilder, app/views/api/v1/invoice_items/show.json.jbuilder, app/views/api/v1/invoices/index.json.jbuilder, app/views/api/v1/invoices/show.json.jbuilder, spec/controllers/api/v1/invoice_items_controller_index_spec.rb, spec/controllers/api/v1/invoice_items_controller_show_spec.rb, spec/controllers/api/v1/invoice_items_find_controller_index_spec.rb, spec/controllers/api/v1/invoice_items_find_controller_show_spec.rb, spec/controllers/api/v1/invoices_controller_index_spec.rb, spec/controllers/api/v1/invoices_controller_show_spec.rb, spec/controllers/api/v1/invoices_find_controller_show_spec.rb, spec/controllers/api/v1/items_controller_index_spec.rb, spec/controllers/api/v1/items_controller_show_spec.rb, spec/controllers/api/v1/items_find_controller_index_spec.rb, spec/controllers/api/v1/items_find_controller_show_spec.rb, spec/factories/factories.rb
Convert InvoiceItems to use Jbuilder. Set to not return `created_at` and `updated_at`. Test this functionality
=> 37 add tests for invoiceitems controller endpoints

app/controllers/api/v1/merchants/invoices_controller.rb, app/controllers/api/v1/merchants/items_controller.rb, app/views/api/v1/merchants/invoices/index.json.jbuilder, app/views/api/v1/merchants/invoices/show.json.jbuilder, app/views/api/v1/merchants/items/index.json.jbuilder, app/views/api/v1/merchants/items/show.json.jbuilder, config/routes.rb, spec/controllers/api/v1/merchants/merchants_invoices_controller_spec.rb, spec/controllers/api/v1/merchants/merchants_items_controller_spec.rb
Add relationship endpoint for Items and for Invoices, both scoped to merchant.  Test these functions.
=> 43 add relationship endpoint to merchant

app/controllers/api/v1/customers/transactions_controller.rb, app/models/customer.rb, app/views/api/v1/customers/transactions/index.json.jbuilder, app/views/api/v1/customers/transactions/show.json.jbuilder, spec/controllers/api/v1/customers_transactions_controller_spec.rb
Add functionality to return a list of Customer's transactions. Test this function.
=> Test Customers->transactions

app/controllers/api/v1/merchants/customers_with_pending_invoices_controller.rb, app/views/api/v1/merchants/customers_with_pending_invoices/index.json.jbuilder, config/routes.rb, spec/controllers/api/v1/customers_with_pending_invoices_controller_spec.rb
*Add CustomersWithPendingInvoicesController
*Add CustomersWithPendingInvoicesController
*Implement Jbuilder view for this features
=> Testing customer with pending invoices

app/controllers/api/v1/merchants/favorite_customer_controller.rb, app/models/customer.rb, app/models/merchant.rb, app/models/transaction.rb, app/views/api/v1/merchants/favorite_customer/show.json.jbuilder, config/routes.rb, spec/controllers/api/v1/customers_with_pending_invoices_controller_spec.rb
Add FavoriteCustomerController. Add `favorite_customer_id` method to Merchant model.
Add relationships between Transaction, Merchant, and Customer.
=> Favorite Customer functionality implemented

app/controllers/api/v1/merchants/customers_with_pending_invoices_controller.rb, app/controllers/api/v1/merchants/most_items_controller.rb, app/controllers/api/v1/merchants/revenues_controller.rb, app/models/customer.rb, app/models/merchant.rb, app/views/api/v1/merchants/most_items/index.json.jbuilder, app/views/api/v1/merchants/revenues/show.json.jbuilder, config/routes.rb, spec/controllers/api/v1/customers_with_pending_invoices_controller_spec.rb
Added first three person A business intelligence methods
=> Person a biz intelligence

spec/controllers/api/v1/customers_with_pending_invoices_controller_spec.rb
Modified CustomersWithPendingInvoices Test to match the changes made to the controller
=> Fixed broken test

app/controllers/api/v1/merchants/revenue_dates_controller.rb, app/models/merchant.rb, app/views/api/v1/merchants/revenue_dates/show.json.jbuilder, config/routes.rb
Add functionality to return revenue across all merchants on a given date.
=> Add revenue all merchants given date

app/controllers/api/v1/merchants/most_revenue_controller.rb, app/models/merchant.rb, app/views/api/v1/merchants/most_revenue/index.json.jbuilder, config/routes.rb
Implement the functionality to return a group of Merchants in order of most to least revenue. The size of the group to return is passed in as a parameter.
=> Implement Most Revenue function

app/channels/application_cable/channel.rb, app/channels/application_cable/connection.rb, app/models/merchant.rb, spec/controllers/api/v1/favorite_customer_controller_spec.rb
Add test for favorite customer controller
=> Test favorite_customer_controller

README.md, app/controllers/api/v1/customers/random_controller.rb, app/controllers/api/v1/invoice_items/random_controller.rb, app/controllers/api/v1/invoices/random_controller.rb, app/controllers/api/v1/items/random_controller.rb, app/controllers/api/v1/merchants/random_controller.rb, app/controllers/api/v1/transactions/random_controller.rb, app/views/api/v1/invoice_items/random/show.json.jbuilder, app/views/api/v1/invoices/random/show.json.jbuilder, app/views/api/v1/items/random/show.json.jbuilder, spec/controllers/api/v1/customer_random_controller_spec.rb, spec/controllers/api/v1/invoice_items_random_controller_spec.rb, spec/controllers/api/v1/invoices_random_controller_spec.rb, spec/controllers/api/v1/items_random_controller_spec.rb, spec/controllers/api/v1/merchants_random_controller_spec.rb, spec/controllers/api/v1/transactions_random_controller_spec.rb
Added tests for each random controller - tested for the structure of the response
=> Add more tests
